#!/usr/bin/env python3

import json
from pathlib import Path
import warnings

import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler


class Config:
    def __init__(self):
        self.y_col = "BASIC_INFO_AGE"
        self.impute_strategy = "median"
        self.setup_paths()

    def setup_paths(self):
        proj_root = Path(__file__).resolve().parents[1]
        self.tbl_merged_path            = proj_root / "data" / "tabular" / "df_merged.csv"
        self.tbl_main_path              = proj_root / "data" / "tabular" / "DATA_ses-01_2025-05-29.csv"
        self.tbl_basic_path             = proj_root / "data" / "tabular" / "Questionnaires_ses-01_number-coding.csv"
        self.tbl_str_path               = proj_root / "data" / "tabular" / "STRUCTURE_VOLUME_MRI_ses-01_2025-05-23.csv"
        self.tbl_motor_path             = proj_root / "data" / "tabular" / "motor_summary_ses-01_new.csv"
        self.tbl_language_path          = proj_root / "data" / "tabular" / "language_summary_ses01.csv"
        self.traintest_split_path       = proj_root / "data" / "meta" / "train-test_subjs.json"
        self.dropped_feature_names_path = proj_root / "data" / "meta" / "preproc_features_dropped.txt"
        self.feature_names_path         = proj_root / "data" / "meta" / "preproc_features.txt"
        self.tbl_out_path               = proj_root / "data" / "tabular" / "df_preproc.csv"


def load_data(paths: dict[str, Path]) -> pd.DataFrame:
    '''
    Load and merge multiple CSV files into a single DataFrame.
    '''
    def _get_col_names(col_type: str) -> list[str]:
        return {
            "basic_info": [
                "AGE", 
                "SEX",
                "LivingPlace", 
                "Education",
                "OccupationStatus",
                "EducationType",
                "Smoking",
                "SmokingYears",
                "SmokingPacksPerDay",
                "UsedToSmokeYear",
                "QuitSmokeYear",
                "UsedToSmokePerDay",
                "Drinking",
                "DrinkingDaysPerWeek",
                "UsedToDrinkYear",
                "UsedToDrinkDayPerWeek",
                "ChronicHTN",
                "ChronicDM",
                "ChronicHLD",
                "InstrumentLearning",
                "InstrumentLearningAge",
                "InstrumentLearningYear",
                "InstrumentType",
                "VideoGamePlaying",
                "VideoGameHourPerWeek",
                "VideoGameController",
                "LanguageDaily", 
                "LanguageNative"
            ], 
            "basic_q": [
                "EHI_Sum", 
                "SF36_PhysicalFunct",
                "SF36_PhysicalLimit",
                "SF36_EmotionalWell",
                "SF36_EmotionalLimit",
                "SF36_Energy",
                "SF36_SocialFunc",
                "SF36_Pain",
                "SF36_GeneralHealth",
                "SF36_Physical",
                "SF36_Mental",
                "PSQI_SleepQuality",
                "PSQI_SleepLatency",
                "PSQI_SleepDuration",
                "PSQI_SleepEfficiency",
                "PSQI_SleepDisturbance",
                "PSQI_SleepMedication",
                "PSQI_DaytimeDysfunc",
                "PSQI_Sum",
                "IPAQ_MET",
                "BFI_Extraversion",
                "BFI_Agreeableness",
                "BFI_Conscientiousness",
                "BFI_EmotionalStability",
                "BFI_Intellect",
                "MSPSS_Sum",
                "CogFailure_Sum",
                "Beck_Anxiety",
                "Beck_Depression"
            ], 
            "structure": [
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulFrontoMargin_VOLUME", 
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulFrontoMargin_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulFrontoMargin_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulOccipitalInf_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulOccipitalInf_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulOccipitalInf_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulParaCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulParaCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulParaCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulSubCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulSubCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulSubCentral_ThickStd", 
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulTransvFrontopol_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulTransvFrontopol_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulTransvFrontopol_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulCingulAnt_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulCingulAnt_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulCingulAnt_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulCingulMidAnt_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulCingulMidAnt_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulCingulMidAnt_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulCingulMidPost_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulCingulMidPost_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySulCingulMidPost_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyCingulPostDorsal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyCingulPostDorsal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyCingulPostDorsal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyCingulPostVentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyCingulPostVentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyCingulPostVentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyCuneus_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyCuneus_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyCuneus_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontInfOpercular_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontInfOpercular_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontInfOpercular_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontInfObital_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontInfObital_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontInfObital_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontInfTriangul_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontInfTriangul_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontInfTriangul_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontMiddle_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontMiddle_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontMiddle_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontSup_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontSup_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyFrontSup_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyInsularLongSulCentralInsular_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyInsularLongSulCentralInsular_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyInsularLongSulCentralInsular_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyInsularShort_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyInsularShort_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyInsularShort_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalMiddle_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalMiddle_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalMiddle_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalSup_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalSup_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalSup_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalTemporalLateralFusifor_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalTemporalLateralFusifor_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalTemporalLateralFusifor_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalTemporalMedialLingual_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalTemporalMedialLingual_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalTemporalMedialLingual_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalTemporalMedialParahip_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalTemporalMedialParahip_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOccipitalTemporalMedialParahip_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOrbital_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOrbital_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyOrbital_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyParietalInfAngular_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyParietalInfAngular_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyParietalInfAngular_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyParietalInfSupramar_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyParietalInfSupramar_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyParietalInfSupramar_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyParietalSuperior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyParietalSuperior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyParietalSuperior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyPostCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyPostCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyPostCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyPreCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyPreCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyPreCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyPreCuneus_VOLUME", 
                "STRUCTURE_NULL_MRI_GM_LEFT_GyPreCuneus_ThickAvg", 
                "STRUCTURE_NULL_MRI_GM_LEFT_GyPreCuneus_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyRectus_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyRectus_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyRectus_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySubcallosal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySubcallosal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GySubcallosal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorGyTemporalTransv_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorGyTemporalTransv_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorGyTemporalTransv_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorLateral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorLateral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorLateral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorPlanPolar_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorPlanPolar_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorPlanPolar_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorPlanTempo_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorPlanTempo_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalSuperiorPlanTempo_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalInferior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalInferior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalInferior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalMiddle_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalMiddle_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_GyTemporalMiddle_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_LateralFisAnterorHorizont_VOLUME", 
                "STRUCTURE_NULL_MRI_GM_LEFT_LateralFisAnterorHorizont_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_LateralFisAnterorHorizont_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_LateralFisAnterorVertical_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_LateralFisAnterorVertical_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_LateralFisAnterorVertical_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_LateralFisPost_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_LateralFisPost_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_LateralFisPost_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_PoleOccipital_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_PoleOccipital_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_PoleOccipital_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_PoleTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_PoleTemporal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_PoleTemporal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCalcarine_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCalcarine_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCalcarine_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCingulMarginalis_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCingulMarginalis_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCingulMarginalis_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCircularInsulaAnteror_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCircularInsulaAnteror_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCircularInsulaAnteror_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCircularInsulaInferior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCircularInsulaInferior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCircularInsulaInferior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCircularInsulaSuperoir_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCircularInsulaSuperoir_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCircularInsulaSuperoir_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCollatTransvAnterior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCollatTransvAnterior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCollatTransvAnterior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCollatTransvPosterior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCollatTransvPosterior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulCollatTransvPosterior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulFrontInferior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulFrontInferior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulFrontInferior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulFrontMiddle_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulFrontMiddle_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulFrontMiddle_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulFrontSuperior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulFrontSuperior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulFrontSuperior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulIntermPrimJensen_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulIntermPrimJensen_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulIntermPrimJensen_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulIntraParietAndParietalTrans_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulIntraParietAndParietalTrans_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulIntraParietAndParietalTrans_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalMiddleAndLunatus_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalMiddleAndLunatus_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalMiddleAndLunatus_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalSuperiorAndTransversal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalSuperiorAndTransversal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalSuperiorAndTransversal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalAnterior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalAnterior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalAnterior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalTemporalLateral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalTemporalLateral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalTemporalLateral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalTemporalMedialAndLingual_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalTemporalMedialAndLingual_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOccipitalTemporalMedialAndLingual_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOrbitalLateral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOrbitalLateral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOrbitalLateral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOrbitalMedialOlfact_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOrbitalMedialOlfact_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOrbitalMedialOlfact_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOrbitalHshaped_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOrbitalHshaped_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulOrbitalHshaped_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulParietoOccipital_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulParietoOccipital_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulParietoOccipital_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPericallosal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPericallosal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPericallosal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPostCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPostCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPostCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPreCentralInferiorPart_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPreCentralInferiorPart_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPreCentralInferiorPart_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPreCentralSuperiorPart_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPreCentralSuperiorPart_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulPreCentralSuperiorPart_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulSubOrbital_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulSubOrbital_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulSubOrbital_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulSubParietal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulSubParietal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulSubParietal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulTemporalInferior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulTemporalInferior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulTemporalInferior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulTemporalSuperior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulTemporalSuperior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulTemporalSuperior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulTemporalTransverse_VOLUME",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulTemporalTransverse_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_LEFT_SulTemporalTransverse_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulFrontoMargin_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulFrontoMargin_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulFrontoMargin_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulOccipitalInf_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulOccipitalInf_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulOccipitalInf_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulParaCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulParaCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulParaCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulSubCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulSubCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulSubCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulTransvFrontopol_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulTransvFrontopol_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulTransvFrontopol_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulCingulAnt_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulCingulAnt_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulCingulAnt_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulCingulMidAnt_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulCingulMidAnt_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulCingulMidAnt_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulCingulMidPost_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulCingulMidPost_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySulCingulMidPost_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyCingulPostDorsal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyCingulPostDorsal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyCingulPostDorsal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyCingulPostVentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyCingulPostVentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyCingulPostVentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyCuneus_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyCuneus_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyCuneus_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontInfOpercular_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontInfOpercular_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontInfOpercular_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontInfObital_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontInfObital_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontInfObital_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontInfTriangul_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontInfTriangul_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontInfTriangul_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontMiddle_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontMiddle_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontMiddle_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontSup_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontSup_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyFrontSup_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyInsularLongSulCentralInsular_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyInsularLongSulCentralInsular_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyInsularLongSulCentralInsular_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyInsularShort_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyInsularShort_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyInsularShort_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalMiddle_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalMiddle_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalMiddle_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalSup_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalSup_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalSup_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalTemporalLateralFusifor_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalTemporalLateralFusifor_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalTemporalLateralFusifor_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalTemporalMedialLingual_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalTemporalMedialLingual_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalTemporalMedialLingual_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalTemporalMedialParahip_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalTemporalMedialParahip_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyOccipitalTemporalMedialParahip_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyORBITAL_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyORBITAL_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyORBITAL_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyParietalInfAngular_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyParietalInfAngular_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyParietalInfAngular_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyParietalInfSupramar_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyParietalInfSupramar_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyParietalInfSupramar_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyParietalSuperior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyParietalSuperior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyParietalSuperior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyPostCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyPostCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyPostCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyPreCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyPreCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyPreCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyPreCuneus_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyPreCuneus_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyPreCuneus_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyRectus_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyRectus_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyRectus_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySubcallosal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySubcallosal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GySubcallosal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorGyTemporalTransv_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorGyTemporalTransv_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorGyTemporalTransv_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorLateral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorLateral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorLateral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorPlanPolar_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorPlanPolar_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorPlanPolar_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorPlanTempo_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorPlanTempo_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalSuperiorPlanTempo_ThickStd", 
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalInferior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalInferior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalInferior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalMiddle_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalMiddle_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_GyTemporalMiddle_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_LateralFisAnterorHorizont_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_LateralFisAnterorHorizont_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_LateralFisAnterorHorizont_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_LateralFisAnterorVertical_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_LateralFisAnterorVertical_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_LateralFisAnterorVertical_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_LateralFisPost_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_LateralFisPost_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_LateralFisPost_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_PoleOccipital_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_PoleOccipital_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_PoleOccipital_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_PoleTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_PoleTemporal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_PoleTemporal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCalcarine_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCalcarine_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCalcarine_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCingulMarginalis_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCingulMarginalis_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCingulMarginalis_ThickStd", 
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCircularInsulaAnteror_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCircularInsulaAnteror_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCircularInsulaAnteror_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCircularInsulaInferior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCircularInsulaInferior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCircularInsulaInferior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCircularInsulaSuperoir_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCircularInsulaSuperoir_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCircularInsulaSuperoir_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCollatTransvAnterior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCollatTransvAnterior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCollatTransvAnterior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCollatTransvPosterior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCollatTransvPosterior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulCollatTransvPosterior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulFrontInferior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulFrontInferior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulFrontInferior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulFrontMiddle_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulFrontMiddle_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulFrontMiddle_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulFrontSuperior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulFrontSuperior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulFrontSuperior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulIntermPrimJensen_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulIntermPrimJensen_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulIntermPrimJensen_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulIntraParietAndParietalTrans_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulIntraParietAndParietalTrans_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulIntraParietAndParietalTrans_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalMiddleAndLunatus_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalMiddleAndLunatus_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalMiddleAndLunatus_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalSuperiorAndTransversal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalSuperiorAndTransversal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalSuperiorAndTransversal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalAnterior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalAnterior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalAnterior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalTemporalLateral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalTemporalLateral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalTemporalLateral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalTemporalMedialAndLingual_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalTemporalMedialAndLingual_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOccipitalTemporalMedialAndLingual_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOrbitalLateral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOrbitalLateral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOrbitalLateral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOrbitalMedialOlfact_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOrbitalMedialOlfact_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOrbitalMedialOlfact_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOrbitalHshaped_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOrbitalHshaped_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulOrbitalHshaped_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulParietoOccipital_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulParietoOccipital_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulParietoOccipital_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPericallosal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPericallosal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPericallosal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPostCentral_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPostCentral_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPostCentral_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPreCentralInferiorPart_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPreCentralInferiorPart_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPreCentralInferiorPart_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPreCentralSuperiorPart_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPreCentralSuperiorPart_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulPreCentralSuperiorPart_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulSubOrbital_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulSubOrbital_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulSubOrbital_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulSubParietal_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulSubParietal_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulSubParietal_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulTemporalInferior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulTemporalInferior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulTemporalInferior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulTemporalSuperior_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulTemporalSuperior_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulTemporalSuperior_ThickStd",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulTemporalTransverse_VOLUME",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulTemporalTransverse_ThickAvg",
                "STRUCTURE_NULL_MRI_GM_RIGHT_SulTemporalTransverse_ThickStd",
                "STRUCTURE_NULL_MRI_WM_LEFT_BanksSuperiorTemporalSul_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_CaudalAnteriorCingulate_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_CaudalMiddleFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_CUNEUS_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_ENTORHINAL_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_FUSIFORM_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_InferiorParietal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_InferiorTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_IsthmusCingulate_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_LateralOccipital_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_LateralOrbitoFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_LINGUAL_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_MedialOrbitoFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_MiddleTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_ParaHippocampal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_ParaCentral_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_ParsOpercularis_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_ParsOrbitalis_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_ParsTriangularis_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_PERICALCARINE_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_PostCentral_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_PosteriorCingulate_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_PreCentral_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_PreCuneus_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_RostralAnteriorCingulate_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_RostralMiddleFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_SuperiorFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_SuperiorParietal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_SuperiorTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_SUPRAMARGINAL_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_FrontalPole_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_TemporalPole_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_TransverseTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_LEFT_INSULA_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_BanksSuperiorTemporalSul_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_CaudalAnteriorCingulate_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_CaudalMiddleFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_CUNEUS_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_ENTORHINAL_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_FUSIFORM_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_InferiorParietal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_InferiorTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_IsthmusCingulate_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_LateralOccipital_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_LateralOrbitoFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_LINGUAL_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_MedialOrbitoFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_MiddleTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_ParaHippocampal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_ParaCentral_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_ParsOpercularis_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_ParsOrbitalis_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_ParsTriangularis_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_PERICALCARINE_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_PostCentral_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_PosteriorCingulate_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_PreCentral_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_PreCuneus_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_RostralAnteriorCingulate_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_RostralMiddleFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_SuperiorFrontal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_SuperiorParietal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_SuperiorTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_SUPRAMARGINAL_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_FrontalPole_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_TemporalPole_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_TransverseTemporal_VOLUME",
                "STRUCTURE_NULL_MRI_WM_RIGHT_INSULA_VOLUME"
            ], 
            "motor": [
                "ST_RAW_BPrestHigh",
                "ST_RAW_BPrestLow",
                "ST_RAW_HRrest",
                "ST_RAW_HEIGHT",
                "ST_RAW_WEIGHT",
                "ST_RAW_BMI",
                "ST_RAW_WHR",
                "ST_RAW_AerobicRating",
                "ST_RAW_FunctionalReaching",
                "ST_RAW_WorseLegEyeOpen",
                "ST_RAW_BestLegEyeOpen",
                "ST_RAW_WorseLegEyeClose",
                "ST_RAW_BestLegEyeClose",
                "ST_RAW_PegboardDominant",
                "ST_RAW_PegboardNondominant",
                "ST_RAW_PegboardBoth",
                "ST_RAW_PegboardSum",
                "ST_RAW_PegboardAssemble",
                "ST_RAW_SymbolSearch",
                "ST_RAW_SymbolCoding",
                "ST_RAW_GripMvcL",
                "ST_RAW_GripMvcR",
                "ST_NORM_BMI",
                "ST_NORM_WHR",
                "ST_NORM_AerobicRating",
                "ST_NORM_FunctionalReaching",
                "ST_NORM_BestLegEyeClose",
                "ST_NORM_PegboardDominant",
                "ST_NORM_PegboardNondominant",
                "ST_NORM_PegboardSum",
                "ST_NORM_PegboardBoth",
                "ST_NORM_PegboardAssemble",
                "ST_NORM_WaisSpeed",
                "ST_SCALED_FineMotor",
                "ST_SCALED_Balance",
                "ST_SCALED_ProcessingSpeed",
                "GFORCE_BEH_LeftLowForce_RT",
                "GFORCE_BEH_LeftLowForce_RTsd",
                "GFORCE_BEH_LeftLowForce_ACC",
                "GFORCE_BEH_LeftLowForce_ACCsd",
                "GFORCE_BEH_LeftHighForce_RT",
                "GFORCE_BEH_LeftHighForce_RTsd",
                "GFORCE_BEH_LeftHighForce_ACC",
                "GFORCE_BEH_LeftHighForce_ACCsd",
                "GFORCE_BEH_RightLowForce_RT",
                "GFORCE_BEH_RightLowForce_RTsd",
                "GFORCE_BEH_RightLowForce_ACC",
                "GFORCE_BEH_RightLowForce_ACCsd",
                "GFORCE_BEH_RightHighForce_RT",
                "GFORCE_BEH_RightHighForce_RTsd",
                "GFORCE_BEH_RightHighForce_ACC",
                "GFORCE_BEH_RightHighForce_ACCsd",
                "GFORCE_MRI_LeftHighForce_LH_CerebVVI_BETA",
                "GFORCE_MRI_LeftHighForce_LH_PMC_BETA",
                "GFORCE_MRI_LeftHighForce_LH_SMA_BETA",
                "GFORCE_MRI_LeftHighForce_LH_insula_BETA",
                "GFORCE_MRI_LeftHighForce_RH_CerebVVI_BETA",
                "GFORCE_MRI_LeftHighForce_RH_PMC_BETA",
                "GFORCE_MRI_LeftHighForce_RH_SMA_BETA",
                "GFORCE_MRI_LeftHighForce_RH_insula_BETA",
                "GFORCE_MRI_LeftLowForce_LH_CerebVVI_BETA",
                "GFORCE_MRI_LeftLowForce_LH_PMC_BETA",
                "GFORCE_MRI_LeftLowForce_LH_SMA_BETA",
                "GFORCE_MRI_LeftLowForce_LH_insula_BETA",
                "GFORCE_MRI_LeftLowForce_RH_CerebVVI_BETA",
                "GFORCE_MRI_LeftLowForce_RH_PMC_BETA",
                "GFORCE_MRI_LeftLowForce_RH_SMA_BETA",
                "GFORCE_MRI_LeftLowForce_RH_insula_BETA",
                "GFORCE_MRI_RightHighForce_LH_CerebVVI_BETA",
                "GFORCE_MRI_RightHighForce_LH_PMC_BETA",
                "GFORCE_MRI_RightHighForce_LH_SMA_BETA",
                "GFORCE_MRI_RightHighForce_LH_insula_BETA",
                "GFORCE_MRI_RightHighForce_RH_CerebVVI_BETA",
                "GFORCE_MRI_RightHighForce_RH_PMC_BETA",
                "GFORCE_MRI_RightHighForce_RH_SMA_BETA",
                "GFORCE_MRI_RightHighForce_RH_insula_BETA",
                "GFORCE_MRI_RightLowForce_LH_CerebVVI_BETA",
                "GFORCE_MRI_RightLowForce_LH_PMC_BETA",
                "GFORCE_MRI_RightLowForce_LH_SMA_BETA",
                "GFORCE_MRI_RightLowForce_LH_insula_BETA",
                "GFORCE_MRI_RightLowForce_RH_CerebVVI_BETA",
                "GFORCE_MRI_RightLowForce_RH_PMC_BETA",
                "GFORCE_MRI_RightLowForce_RH_SMA_BETA",
                "GFORCE_MRI_RightLowForce_RH_insula_BETA",
                "GFORCE_MRI_LeftHighForce_LH_CerebVVI_VoxelCount",
                "GFORCE_MRI_LeftHighForce_LH_PMC_VoxelCount",
                "GFORCE_MRI_LeftHighForce_LH_SMA_VoxelCount",
                "GFORCE_MRI_LeftHighForce_LH_insula_VoxelCount",
                "GFORCE_MRI_LeftHighForce_RH_CerebVVI_VoxelCount",
                "GFORCE_MRI_LeftHighForce_RH_PMC_VoxelCount",
                "GFORCE_MRI_LeftHighForce_RH_SMA_VoxelCount",
                "GFORCE_MRI_LeftHighForce_RH_insula_VoxelCount",
                "GFORCE_MRI_LeftLowForce_LH_CerebVVI_VoxelCount",
                "GFORCE_MRI_LeftLowForce_LH_PMC_VoxelCount",
                "GFORCE_MRI_LeftLowForce_LH_SMA_VoxelCount",
                "GFORCE_MRI_LeftLowForce_LH_insula_VoxelCount",
                "GFORCE_MRI_LeftLowForce_RH_CerebVVI_VoxelCount",
                "GFORCE_MRI_LeftLowForce_RH_PMC_VoxelCount",
                "GFORCE_MRI_LeftLowForce_RH_SMA_VoxelCount",
                "GFORCE_MRI_LeftLowForce_RH_insula_VoxelCount",
                "GFORCE_MRI_RightHighForce_LH_CerebVVI_VoxelCount",
                "GFORCE_MRI_RightHighForce_LH_PMC_VoxelCount",
                "GFORCE_MRI_RightHighForce_LH_SMA_VoxelCount",
                "GFORCE_MRI_RightHighForce_LH_insula_VoxelCount",
                "GFORCE_MRI_RightHighForce_RH_CerebVVI_VoxelCount",
                "GFORCE_MRI_RightHighForce_RH_PMC_VoxelCount",
                "GFORCE_MRI_RightHighForce_RH_SMA_VoxelCount",
                "GFORCE_MRI_RightHighForce_RH_insula_VoxelCount",
                "GFORCE_MRI_RightLowForce_LH_CerebVVI_VoxelCount",
                "GFORCE_MRI_RightLowForce_LH_PMC_VoxelCount",
                "GFORCE_MRI_RightLowForce_LH_SMA_VoxelCount",
                "GFORCE_MRI_RightLowForce_LH_insula_VoxelCount",
                "GFORCE_MRI_RightLowForce_RH_CerebVVI_VoxelCount",
                "GFORCE_MRI_RightLowForce_RH_PMC_VoxelCount",
                "GFORCE_MRI_RightLowForce_RH_SMA_VoxelCount",
                "GFORCE_MRI_RightLowForce_RH_insula_VoxelCount",
                "GOFITTS_EEG_CueSlope_P3_N200Time_NULL",
                "GOFITTS_EEG_CueSlope_P3_N200Amp_NULL",
                "GOFITTS_EEG_CueSlope_P3_P300Time_NULL",
                "GOFITTS_EEG_CueSlope_P3_P300Amp_NULL",
                "GOFITTS_EEG_CueSlope_P3_DiffTime_NULL",
                "GOFITTS_EEG_CueSlope_P3_DiffAmp_NULL",
                "GOFITTS_EEG_CueSlopeW3_P3_N200Time_NULL",
                "GOFITTS_EEG_CueSlopeW3_P3_N200Amp_NULL",
                "GOFITTS_EEG_CueSlopeW3_P3_P300Time_NULL",
                "GOFITTS_EEG_CueSlopeW3_P3_P300Amp_NULL",
                "GOFITTS_EEG_CueSlopeW3_P3_DiffTime_NULL",
                "GOFITTS_EEG_CueSlopeW3_P3_DiffAmp_NULL",
                "GOFITTS_EEG_CueSlopeW2_P3_N200Time_NULL",
                "GOFITTS_EEG_CueSlopeW2_P3_N200Amp_NULL",
                "GOFITTS_EEG_CueSlopeW2_P3_P300Time_NULL",
                "GOFITTS_EEG_CueSlopeW2_P3_P300Amp_NULL",
                "GOFITTS_EEG_CueSlopeW2_P3_DiffTime_NULL",
                "GOFITTS_EEG_CueSlopeW2_P3_DiffAmp_NULL",
                "GOFITTS_EEG_CueSlope_P4_N200Time_NULL",
                "GOFITTS_EEG_CueSlope_P4_N200Amp_NULL",
                "GOFITTS_EEG_CueSlope_P4_P300Time_NULL",
                "GOFITTS_EEG_CueSlope_P4_P300Amp_NULL",
                "GOFITTS_EEG_CueSlope_P4_DiffTime_NULL",
                "GOFITTS_EEG_CueSlope_P4_DiffAmp_NULL",
                "GOFITTS_EEG_CueSlopeW3_P4_N200Time_NULL",
                "GOFITTS_EEG_CueSlopeW3_P4_N200Amp_NULL",
                "GOFITTS_EEG_CueSlopeW3_P4_P300Time_NULL",
                "GOFITTS_EEG_CueSlopeW3_P4_P300Amp_NULL",
                "GOFITTS_EEG_CueSlopeW3_P4_DiffTime_NULL",
                "GOFITTS_EEG_CueSlopeW3_P4_DiffAmp_NULL",
                "GOFITTS_EEG_CueSlopeW2_P4_N200Time_NULL",
                "GOFITTS_EEG_CueSlopeW2_P4_N200Amp_NULL",
                "GOFITTS_EEG_CueSlopeW2_P4_P300Time_NULL",
                "GOFITTS_EEG_CueSlopeW2_P4_P300Amp_NULL",
                "GOFITTS_EEG_CueSlopeW2_P4_DiffTime_NULL",
                "GOFITTS_EEG_CueSlopeW2_P4_DiffAmp_NULL",
                "GOFITTS_EEG_GoSlope_P3_N200Time_NULL",
                "GOFITTS_EEG_GoSlope_P3_N200Amp_NULL",
                "GOFITTS_EEG_GoSlope_P3_P300Time_NULL",
                "GOFITTS_EEG_GoSlope_P3_P300Amp_NULL",
                "GOFITTS_EEG_GoSlope_P3_DiffTime_NULL",
                "GOFITTS_EEG_GoSlope_P3_DiffAmp_NULL",
                "GOFITTS_EEG_GoSlopeW3_P3_N200Time_NULL",
                "GOFITTS_EEG_GoSlopeW3_P3_N200Amp_NULL",
                "GOFITTS_EEG_GoSlopeW3_P3_P300Time_NULL",
                "GOFITTS_EEG_GoSlopeW3_P3_P300Amp_NULL",
                "GOFITTS_EEG_GoSlopeW3_P3_DiffTime_NULL",
                "GOFITTS_EEG_GoSlopeW3_P3_DiffAmp_NULL",
                "GOFITTS_EEG_GoSlopeW2_P3_N200Time_NULL",
                "GOFITTS_EEG_GoSlopeW2_P3_N200Amp_NULL",
                "GOFITTS_EEG_GoSlopeW2_P3_P300Time_NULL",
                "GOFITTS_EEG_GoSlopeW2_P3_P300Amp_NULL",
                "GOFITTS_EEG_GoSlopeW2_P3_DiffTime_NULL",
                "GOFITTS_EEG_GoSlopeW2_P3_DiffAmp_NULL",
                "GOFITTS_EEG_GoSlope_P4_N200Time_NULL",
                "GOFITTS_EEG_GoSlope_P4_N200Amp_NULL",
                "GOFITTS_EEG_GoSlope_P4_P300Time_NULL",
                "GOFITTS_EEG_GoSlope_P4_P300Amp_NULL",
                "GOFITTS_EEG_GoSlope_P4_DiffTime_NULL",
                "GOFITTS_EEG_GoSlope_P4_DiffAmp_NULL",
                "GOFITTS_EEG_GoSlopeW3_P4_N200Time_NULL",
                "GOFITTS_EEG_GoSlopeW3_P4_N200Amp_NULL",
                "GOFITTS_EEG_GoSlopeW3_P4_P300Time_NULL",
                "GOFITTS_EEG_GoSlopeW3_P4_P300Amp_NULL",
                "GOFITTS_EEG_GoSlopeW3_P4_DiffTime_NULL",
                "GOFITTS_EEG_GoSlopeW3_P4_DiffAmp_NULL",
                "GOFITTS_EEG_GoSlopeW2_P4_N200Time_NULL",
                "GOFITTS_EEG_GoSlopeW2_P4_N200Amp_NULL",
                "GOFITTS_EEG_GoSlopeW2_P4_P300Time_NULL",
                "GOFITTS_EEG_GoSlopeW2_P4_P300Amp_NULL",
                "GOFITTS_EEG_GoSlopeW2_P4_DiffTime_NULL",
                "GOFITTS_EEG_GoSlopeW2_P4_DiffAmp_NULL",
                "GOFITTS_EEG_CueID1_P3_N200Time_NULL",
                "GOFITTS_EEG_CueID2_P3_N200Time_NULL",
                "GOFITTS_EEG_CueID3_P3_N200Time_NULL",
                "GOFITTS_EEG_CueID4_P3_N200Time_NULL",
                "GOFITTS_EEG_CueID5_P3_N200Time_NULL",
                "GOFITTS_EEG_CueID6_P3_N200Time_NULL",
                "GOFITTS_EEG_CueID1_P3_N200Amp_NULL",
                "GOFITTS_EEG_CueID2_P3_N200Amp_NULL",
                "GOFITTS_EEG_CueID3_P3_N200Amp_NULL",
                "GOFITTS_EEG_CueID4_P3_N200Amp_NULL",
                "GOFITTS_EEG_CueID5_P3_N200Amp_NULL",
                "GOFITTS_EEG_CueID6_P3_N200Amp_NULL",
                "GOFITTS_EEG_CueID1_P3_P300Time_NULL",
                "GOFITTS_EEG_CueID2_P3_P300Time_NULL",
                "GOFITTS_EEG_CueID3_P3_P300Time_NULL",
                "GOFITTS_EEG_CueID4_P3_P300Time_NULL",
                "GOFITTS_EEG_CueID5_P3_P300Time_NULL",
                "GOFITTS_EEG_CueID6_P3_P300Time_NULL",
                "GOFITTS_EEG_CueID1_P3_P300Amp_NULL",
                "GOFITTS_EEG_CueID2_P3_P300Amp_NULL",
                "GOFITTS_EEG_CueID3_P3_P300Amp_NULL",
                "GOFITTS_EEG_CueID4_P3_P300Amp_NULL",
                "GOFITTS_EEG_CueID5_P3_P300Amp_NULL",
                "GOFITTS_EEG_CueID6_P3_P300Amp_NULL",
                "GOFITTS_EEG_CueID1_P3_DiffTime_NULL",
                "GOFITTS_EEG_CueID2_P3_DiffTime_NULL",
                "GOFITTS_EEG_CueID3_P3_DiffTime_NULL",
                "GOFITTS_EEG_CueID4_P3_DiffTime_NULL",
                "GOFITTS_EEG_CueID5_P3_DiffTime_NULL",
                "GOFITTS_EEG_CueID6_P3_DiffTime_NULL",
                "GOFITTS_EEG_CueID1_P3_DiffAmp_NULL",
                "GOFITTS_EEG_CueID2_P3_DiffAmp_NULL",
                "GOFITTS_EEG_CueID3_P3_DiffAmp_NULL",
                "GOFITTS_EEG_CueID4_P3_DiffAmp_NULL",
                "GOFITTS_EEG_CueID5_P3_DiffAmp_NULL",
                "GOFITTS_EEG_CueID6_P3_DiffAmp_NULL",
                "GOFITTS_EEG_CueID1_P4_N200Time_NULL",
                "GOFITTS_EEG_CueID2_P4_N200Time_NULL",
                "GOFITTS_EEG_CueID3_P4_N200Time_NULL",
                "GOFITTS_EEG_CueID4_P4_N200Time_NULL",
                "GOFITTS_EEG_CueID5_P4_N200Time_NULL",
                "GOFITTS_EEG_CueID6_P4_N200Time_NULL",
                "GOFITTS_EEG_CueID1_P4_N200Amp_NULL",
                "GOFITTS_EEG_CueID2_P4_N200Amp_NULL",
                "GOFITTS_EEG_CueID3_P4_N200Amp_NULL",
                "GOFITTS_EEG_CueID4_P4_N200Amp_NULL",
                "GOFITTS_EEG_CueID5_P4_N200Amp_NULL",
                "GOFITTS_EEG_CueID6_P4_N200Amp_NULL",
                "GOFITTS_EEG_CueID1_P4_P300Time_NULL",
                "GOFITTS_EEG_CueID2_P4_P300Time_NULL",
                "GOFITTS_EEG_CueID3_P4_P300Time_NULL",
                "GOFITTS_EEG_CueID4_P4_P300Time_NULL",
                "GOFITTS_EEG_CueID5_P4_P300Time_NULL",
                "GOFITTS_EEG_CueID6_P4_P300Time_NULL",
                "GOFITTS_EEG_CueID1_P4_P300Amp_NULL",
                "GOFITTS_EEG_CueID2_P4_P300Amp_NULL",
                "GOFITTS_EEG_CueID3_P4_P300Amp_NULL",
                "GOFITTS_EEG_CueID4_P4_P300Amp_NULL",
                "GOFITTS_EEG_CueID5_P4_P300Amp_NULL",
                "GOFITTS_EEG_CueID6_P4_P300Amp_NULL",
                "GOFITTS_EEG_CueID1_P4_DiffTime_NULL",
                "GOFITTS_EEG_CueID2_P4_DiffTime_NULL",
                "GOFITTS_EEG_CueID3_P4_DiffTime_NULL",
                "GOFITTS_EEG_CueID4_P4_DiffTime_NULL",
                "GOFITTS_EEG_CueID5_P4_DiffTime_NULL",
                "GOFITTS_EEG_CueID6_P4_DiffTime_NULL",
                "GOFITTS_EEG_CueID1_P4_DiffAmp_NULL",
                "GOFITTS_EEG_CueID2_P4_DiffAmp_NULL",
                "GOFITTS_EEG_CueID3_P4_DiffAmp_NULL",
                "GOFITTS_EEG_CueID4_P4_DiffAmp_NULL",
                "GOFITTS_EEG_CueID5_P4_DiffAmp_NULL",
                "GOFITTS_EEG_CueID6_P4_DiffAmp_NULL",
                "GOFITTS_EEG_GoID1_P3_N200Time_NULL",
                "GOFITTS_EEG_GoID2_P3_N200Time_NULL",
                "GOFITTS_EEG_GoID3_P3_N200Time_NULL",
                "GOFITTS_EEG_GoID4_P3_N200Time_NULL",
                "GOFITTS_EEG_GoID5_P3_N200Time_NULL",
                "GOFITTS_EEG_GoID6_P3_N200Time_NULL",
                "GOFITTS_EEG_GoID1_P3_N200Amp_NULL",
                "GOFITTS_EEG_GoID2_P3_N200Amp_NULL",
                "GOFITTS_EEG_GoID3_P3_N200Amp_NULL",
                "GOFITTS_EEG_GoID4_P3_N200Amp_NULL",
                "GOFITTS_EEG_GoID5_P3_N200Amp_NULL",
                "GOFITTS_EEG_GoID6_P3_N200Amp_NULL",
                "GOFITTS_EEG_GoID1_P3_P300Time_NULL",
                "GOFITTS_EEG_GoID2_P3_P300Time_NULL",
                "GOFITTS_EEG_GoID3_P3_P300Time_NULL",
                "GOFITTS_EEG_GoID4_P3_P300Time_NULL",
                "GOFITTS_EEG_GoID5_P3_P300Time_NULL",
                "GOFITTS_EEG_GoID6_P3_P300Time_NULL",
                "GOFITTS_EEG_GoID1_P3_P300Amp_NULL",
                "GOFITTS_EEG_GoID2_P3_P300Amp_NULL",
                "GOFITTS_EEG_GoID3_P3_P300Amp_NULL",
                "GOFITTS_EEG_GoID4_P3_P300Amp_NULL",
                "GOFITTS_EEG_GoID5_P3_P300Amp_NULL",
                "GOFITTS_EEG_GoID6_P3_P300Amp_NULL",
                "GOFITTS_EEG_GoID1_P3_DiffTime_NULL",
                "GOFITTS_EEG_GoID2_P3_DiffTime_NULL",
                "GOFITTS_EEG_GoID3_P3_DiffTime_NULL",
                "GOFITTS_EEG_GoID4_P3_DiffTime_NULL",
                "GOFITTS_EEG_GoID5_P3_DiffTime_NULL",
                "GOFITTS_EEG_GoID6_P3_DiffTime_NULL",
                "GOFITTS_EEG_GoID1_P3_DiffAmp_NULL",
                "GOFITTS_EEG_GoID2_P3_DiffAmp_NULL",
                "GOFITTS_EEG_GoID3_P3_DiffAmp_NULL",
                "GOFITTS_EEG_GoID4_P3_DiffAmp_NULL",
                "GOFITTS_EEG_GoID5_P3_DiffAmp_NULL",
                "GOFITTS_EEG_GoID6_P3_DiffAmp_NULL",
                "GOFITTS_EEG_GoID1_P4_N200Time_NULL",
                "GOFITTS_EEG_GoID2_P4_N200Time_NULL",
                "GOFITTS_EEG_GoID3_P4_N200Time_NULL",
                "GOFITTS_EEG_GoID4_P4_N200Time_NULL",
                "GOFITTS_EEG_GoID5_P4_N200Time_NULL",
                "GOFITTS_EEG_GoID6_P4_N200Time_NULL",
                "GOFITTS_EEG_GoID1_P4_N200Amp_NULL",
                "GOFITTS_EEG_GoID2_P4_N200Amp_NULL",
                "GOFITTS_EEG_GoID3_P4_N200Amp_NULL",
                "GOFITTS_EEG_GoID4_P4_N200Amp_NULL",
                "GOFITTS_EEG_GoID5_P4_N200Amp_NULL",
                "GOFITTS_EEG_GoID6_P4_N200Amp_NULL",
                "GOFITTS_EEG_GoID1_P4_P300Time_NULL",
                "GOFITTS_EEG_GoID2_P4_P300Time_NULL",
                "GOFITTS_EEG_GoID3_P4_P300Time_NULL",
                "GOFITTS_EEG_GoID4_P4_P300Time_NULL",
                "GOFITTS_EEG_GoID5_P4_P300Time_NULL",
                "GOFITTS_EEG_GoID6_P4_P300Time_NULL",
                "GOFITTS_EEG_GoID1_P4_P300Amp_NULL",
                "GOFITTS_EEG_GoID2_P4_P300Amp_NULL",
                "GOFITTS_EEG_GoID3_P4_P300Amp_NULL",
                "GOFITTS_EEG_GoID4_P4_P300Amp_NULL",
                "GOFITTS_EEG_GoID5_P4_P300Amp_NULL",
                "GOFITTS_EEG_GoID6_P4_P300Amp_NULL",
                "GOFITTS_EEG_GoID1_P4_DiffTime_NULL",
                "GOFITTS_EEG_GoID2_P4_DiffTime_NULL",
                "GOFITTS_EEG_GoID3_P4_DiffTime_NULL",
                "GOFITTS_EEG_GoID4_P4_DiffTime_NULL",
                "GOFITTS_EEG_GoID5_P4_DiffTime_NULL",
                "GOFITTS_EEG_GoID6_P4_DiffTime_NULL",
                "GOFITTS_EEG_GoID1_P4_DiffAmp_NULL",
                "GOFITTS_EEG_GoID2_P4_DiffAmp_NULL",
                "GOFITTS_EEG_GoID3_P4_DiffAmp_NULL",
                "GOFITTS_EEG_GoID4_P4_DiffAmp_NULL",
                "GOFITTS_EEG_GoID5_P4_DiffAmp_NULL",
                "GOFITTS_EEG_GoID6_P4_DiffAmp_NULL",
                "GOFITTS_BEH_ID1_LeaveTime",
                "GOFITTS_BEH_ID2_LeaveTime",
                "GOFITTS_BEH_ID3_LeaveTime",
                "GOFITTS_BEH_ID4_LeaveTime",
                "GOFITTS_BEH_ID5_LeaveTime",
                "GOFITTS_BEH_ID6_LeaveTime",
                "GOFITTS_BEH_ID1_PointTime",
                "GOFITTS_BEH_ID2_PointTime",
                "GOFITTS_BEH_ID3_PointTime",
                "GOFITTS_BEH_ID4_PointTime",
                "GOFITTS_BEH_ID5_PointTime",
                "GOFITTS_BEH_ID6_PointTime",
                "GOFITTS_BEH_ID1_Throughput",
                "GOFITTS_BEH_ID2_Throughput",
                "GOFITTS_BEH_ID3_Throughput",
                "GOFITTS_BEH_ID4_Throughput",
                "GOFITTS_BEH_ID5_Throughput",
                "GOFITTS_BEH_ID6_Throughput",
                "GOFITTS_BEH_SLOPE_LeaveTime",
                "GOFITTS_BEH_SLOPE_PointTime",
                "GOFITTS_BEH_SLOPE_LeaveTimeW3",
                "GOFITTS_BEH_SLOPE_LeaveTimeW2",
                "GOFITTS_BEH_SLOPE_PointTimeW3",
                "GOFITTS_BEH_SLOPE_PointTimeW2",
                "BILPRESS_BEH_HighForceSyncing_ReachTime",
                "BILPRESS_BEH_HighForceSyncing_VARIABILITY",
                "BILPRESS_BEH_HighForceStable_VARIABILITY",
                "BILPRESS_BEH_LowForceSyncing_ReachTime",
                "BILPRESS_BEH_LowForceSyncing_VARIABILITY",
                "BILPRESS_BEH_LowForceStable_VARIABILITY",
                "BILPRESS_EEG_HighForceStable_C3_NULL_ALPHA",
                "BILPRESS_EEG_HighForceStable_C3_NULL_BETA",
                "BILPRESS_EEG_HighForceStable_C4_NULL_ALPHA",
                "BILPRESS_EEG_HighForceStable_C4_NULL_BETA",
                "BILPRESS_EEG_HighForceSyncing_C3_NULL_ALPHA",
                "BILPRESS_EEG_HighForceSyncing_C3_NULL_BETA",
                "BILPRESS_EEG_HighForceSyncing_C4_NULL_ALPHA",
                "BILPRESS_EEG_HighForceSyncing_C4_NULL_BETA",
                "BILPRESS_EEG_LowForceStable_C3_NULL_ALPHA",
                "BILPRESS_EEG_LowForceStable_C3_NULL_BETA",
                "BILPRESS_EEG_LowForceStable_C4_NULL_ALPHA",
                "BILPRESS_EEG_LowForceStable_C4_NULL_BETA",
                "BILPRESS_EEG_LowForceSyncing_C3_NULL_ALPHA",
                "BILPRESS_EEG_LowForceSyncing_C3_NULL_BETA",
                "BILPRESS_EEG_LowForceSyncing_C4_NULL_ALPHA",
                "BILPRESS_EEG_LowForceSyncing_C4_NULL_BETA",
                "BILPRESS_EEG_LowForceSyncing_C3C4Diff_NULL_ALPHA",
                "BILPRESS_EEG_HighForceSyncing_C3C4Diff_NULL_ALPHA",
                "BILPRESS_EEG_LowForceSyncing_C3C4Diff_NULL_BETA",
                "BILPRESS_EEG_HighForceSyncing_C3C4Diff_NULL_BETA",
                "BILPRESS_EEG_LowForceStable_C3C4Diff_NULL_ALPHA",
                "BILPRESS_EEG_HighForceStable_C3C4Diff_NULL_ALPHA",
                "BILPRESS_EEG_LowForceStable_C3C4Diff_NULL_BETA",
                "BILPRESS_EEG_HighForceStable_C3C4Diff_NULL_BETA",
                "BILPRESS_EEG_HighForceStable_PSI_NULL_ALPHA",
                "BILPRESS_EEG_HighForceStable_PSI_NULL_BETA",
                "BILPRESS_EEG_HighForceSyncing_PSI_NULL_ALPHA",
                "BILPRESS_EEG_HighForceSyncing_PSI_NULL_BETA",
                "BILPRESS_EEG_LowForceStable_PSI_NULL_ALPHA",
                "BILPRESS_EEG_LowForceStable_PSI_NULL_BETA",
                "BILPRESS_EEG_LowForceSyncing_PSI_NULL_ALPHA",
                "BILPRESS_EEG_LowForceSyncing_PSI_NULL_BETA",
            ], 
            "language": [
                "ST_RAW_SIMILARITY",
                "ST_RAW_VOCABULARY",
                "ST_RAW_INFORMATION",
                "ST_RAW_SUM",
                "ST_SCALED_SIMILARITY",
                "ST_SCALED_VOCABULARY",
                "ST_SCALED_INFORMATION",
                "ST_SCALED_SUM",
                "ST_NORM_SIMILARITY",
                "ST_NORM_VOCABULARY",
                "ST_NORM_INFORMATION",
                "ST_NORM_VCI",
                "ST_NORM_PR",
                "READING_BEH_NULL_MeanSR",
                "STORY_BEH_NULL_MeanSR",
                "WORDNAME_BEH_HFHC_ACCURACY",
                "WORDNAME_BEH_HFLC_ACCURACY",
                "WORDNAME_BEH_LFHC_ACCURACY",
                "WORDNAME_BEH_LFLC_ACCURACY",
                "SPEECHCOMP_BEH_ACTION_ACCURACY",
                "SPEECHCOMP_BEH_OBJECT_ACCURACY",
                "SPEECHCOMP_BEH_PASSIVE_ACCURACY",
                "SPEECHCOMP_BEH_CONTROL_ACCURACY",
                "WORDNAME_BEH_HFHC_RT",
                "WORDNAME_BEH_HFLC_RT",
                "WORDNAME_BEH_LFHC_RT",
                "WORDNAME_BEH_LFLC_RT",
                "WORDNAME_MRI_HFHC_BROCA_BETA",
                "WORDNAME_MRI_HFLC_BROCA_BETA",
                "WORDNAME_MRI_LFHC_BROCA_BETA",
                "WORDNAME_MRI_LFLC_BROCA_BETA",
                "WORDNAME_MRI_DiffLFHF_BROCA_BETA",
                "WORDNAME_MRI_DiffLCHC_BROCA_BETA",
                "SPEECHCOMP_MRI_ACTION_BROCA_BETA",
                "SPEECHCOMP_MRI_OBJECT_BROCA_BETA",
                "SPEECHCOMP_MRI_PASSIVE_BROCA_BETA",
                "SPEECHCOMP_MRI_CONTROL_BROCA_BETA",
                "SPEECHCOMP_MRI_DiffAC_BROCA_BETA",
                "SPEECHCOMP_MRI_DiffOC_BROCA_BETA",
                "SPEECHCOMP_MRI_DiffPC_BROCA_BETA",
                "WORDNAME_MRI_HFHC_WERNICKE_BETA",
                "WORDNAME_MRI_HFLC_WERNICKE_BETA",
                "WORDNAME_MRI_LFHC_WERNICKE_BETA",
                "WORDNAME_MRI_LFLC_WERNICKE_BETA",
                "WORDNAME_MRI_DiffLFHF_WERNICKE_BETA",
                "WORDNAME_MRI_DiffLCHC_WERNICKE_BETA",
                "SPEECHCOMP_MRI_ACTION_WERNICKE_BETA",
                "SPEECHCOMP_MRI_OBJECT_WERNICKE_BETA",
                "SPEECHCOMP_MRI_PASSIVE_WERNICKE_BETA",
                "SPEECHCOMP_MRI_CONTROL_WERNICKE_BETA",
                "SPEECHCOMP_MRI_DiffAC_WERNICKE_BETA",
                "SPEECHCOMP_MRI_DiffOC_WERNICKE_BETA",
                "SPEECHCOMP_MRI_DiffPC_WERNICKE_BETA",
                "WORDNAME_MRI_HFHC_LeftAntTemporalPole_BETA",
                "WORDNAME_MRI_HFLC_LeftAntTemporalPole_BETA",
                "WORDNAME_MRI_LFHC_LeftAntTemporalPole_BETA",
                "WORDNAME_MRI_LFLC_LeftAntTemporalPole_BETA",
                "WORDNAME_MRI_DiffLFHF_LeftAntTemporalPole_BETA",
                "WORDNAME_MRI_DiffLCHC_LeftAntTemporalPole_BETA",
                "SPEECHCOMP_MRI_ACTION_LeftAntTemporalPole_BETA",
                "SPEECHCOMP_MRI_OBJECT_LeftAntTemporalPole_BETA",
                "SPEECHCOMP_MRI_PASSIVE_LeftAntTemporalPole_BETA",
                "SPEECHCOMP_MRI_CONTROL_LeftAntTemporalPole_BETA",
                "SPEECHCOMP_MRI_DiffAC_LeftAntTemporalPole_BETA",
                "SPEECHCOMP_MRI_DiffOC_LeftAntTemporalPole_BETA",
                "SPEECHCOMP_MRI_DiffPC_LeftAntTemporalPole_BETA",
            ]
        }[col_type]

    df = pd.read_csv(paths["main"], index_col=0)

    df_basic = pd.read_csv(paths["basic"], index_col=0)
    df_basic = df_basic.rename(columns={ c: f"BASIC_INFO_{c}" for c in _get_col_names("basic_info") })
    df_basic = df_basic.rename(columns={ c: f"BASIC_Q_{c}" for c in _get_col_names("basic_q") })
    df.update(df_basic)

    df_str = pd.read_csv(paths["structure"], index_col=0)
    df_str = df_str.rename(columns={ c: f"STRUCTURE_{c}" for c in _get_col_names("structure") })
    df.update(df_str)

    df_motor = pd.read_csv(paths["motor"], index_col=0)
    df_motor = df_motor.rename(columns={ c: f"MOTOR_{c}" for c in _get_col_names("motor") })
    df.update(df_motor)

    df_language = pd.read_csv(paths["language"], index_col=0)
    df_language = df_language.rename(columns={ c: f"LANGUAGE_{c}" for c in _get_col_names("language") })
    df.update(df_language)

    return df


def drop_cols(df: pd.DataFrame) -> pd.DataFrame:
    return df.drop(columns=[
        c for c in df.columns if 
        ( c.startswith("BASIC_") and (c not in ["BASIC_INFO_AGE", "BASIC_INFO_SEX"]) )
        or ( "_ST_" in c )
    ])


def split_data(traintest_split_path: Path, df: pd.DataFrame):
    with open(traintest_split_path, "r") as f:
        split_idxs = json.load(f)

    return (
        df.loc[split_idxs["train"], :], 
        df.loc[split_idxs["test"], :]
    )


def remove_outlier_features(df_train, df_test):
    na_rates = pd.Series(df_train.isnull().sum() / len(df_train))
    q1 = na_rates.quantile(.25)
    q3 = na_rates.quantile(.75)
    iqr = q3 - q1
    outliers = na_rates[na_rates > (q3 + iqr*1.5)]

    return (
        df_train.drop(columns=outliers.index), 
        df_test.drop(columns=outliers.index), 
        outliers.index
    )


def fill_missing(df_train, df_test, features, impute_strategy):
    imputer = SimpleImputer(strategy=impute_strategy)
    df_train.loc[:, features] = imputer.fit_transform(df_train.loc[:, features])
    df_test.loc[:, features] = imputer.transform(df_test.loc[:, features])
    
    return df_train, df_test


def scale_features(df_train, df_test, features):
    scaler = StandardScaler()
    df_train.loc[:, features] = scaler.fit_transform(df_train.loc[:, features])
    df_test.loc[:, features] = scaler.transform(df_test.loc[:, features])
    
    return df_train, df_test


def main():
    config = Config()

    if config.tbl_merged_path.exists():
        data = pd.read_csv(config.tbl_merged_path, index_col=0)
    else:
        data = load_data({
            "main": config.tbl_main_path, 
            "basic": config.tbl_basic_path, 
            "structure": config.tbl_str_path,
            "motor": config.tbl_motor_path, 
            "language": config.tbl_language_path
        })
        data.to_csv(config.tbl_merged_path)

    assert config.y_col in data.columns, f"Target column '{config.y_col}' not in the dataset."
    
    data = drop_cols(data)
    df_train, df_test = split_data(config.traintest_split_path, data)

    df_train, df_test, outlier_features = remove_outlier_features(df_train, df_test)
    features = [ c for c in df_train.columns if c not in ["BASIC_INFO_AGE", "BASIC_INFO_SEX"] ]
    with open(config.dropped_feature_names_path, "w") as f:
        f.write("\n".join(outlier_features))
    with open(config.feature_names_path, "w") as f:
        f.write("\n".join(features))

    df_train, df_test = fill_missing(df_train, df_test, features, config.impute_strategy)
    df_train, df_test = scale_features(df_train, df_test, features)
    
    df_train.insert(0, "Set", "train")
    df_test.insert(0, "Set", "test")
    config.tbl_out_path.parent.mkdir(parents=True, exist_ok=True)
    pd.concat([df_train, df_test], axis=0).to_csv(config.tbl_out_path)


if __name__ == "__main__":
    warnings.filterwarnings("ignore")
    main()
    print("\nFinish data preprocessing.\n")